package com.coachdiff.domain.model;

public record MatchRecord(
    String matchId,
    String puuid,
    boolean win,
    double gameDurationMinutes,
    String championName,
    Role role,
    int kills,
    int deaths,
    int assists,
    double kda,
    int soloKills,
    double damagePerMinute,
    double damagePerGold,
    double teamDamagePercentage,
    double damageTakenPercentage,
    double killParticipation,
    double goldPerMinute,
    double csPerMinute,
    int damageToTurrets,
    int damageToObjectives,
    int turretPlatesTaken,
    double visionScorePerMinute,
    int wardsPlaced,
    int wardsKilled,
    int controlWardsPlaced,
    Double csAt10,
    Double goldAt10,
    Double goldAt15,
    Double xpAt15) {}
